const students = [
    {
        "id": 1,
        "rollNo": "2500460140001",
        "name": "Aashutosh Dubey",
        "gender": "Male",
        "phone": "9555874036",
        "tenthPercentage": "85%",
        "tenthBoard": "UP Board",
        "interPercentage": "69%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "79%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 8.17,
        "cgpa2": 8.43, "dob":"02-12-2006"
    },
    {
        "id": 2,
        "rollNo": "2500460140002",
        "name": "Abhinesh Yadav",
        "gender": "Male",
        "phone": "7522065510",
        "tenthPercentage": "82%",
        "tenthBoard": "UP Board",
        "interPercentage": "61%",
        "interBoard": "UP ",
        "course": "BSC",
        "graduationPercentage": "79.71%",
        "university": "CSJMU",
        "medium": "English ",
        "cgpa1": 7.7,
        "cgpa2": 7.3
    },
    {
        "id": 3,
        "rollNo": "2500460140003",
        "name": "Akash Dwivedi",
        "gender": "Male",
        "phone": "8423173217",
        "tenthPercentage": "80.6%",
        "tenthBoard": "UP board",
        "interPercentage": "77.9%",
        "interBoard": "UP",
        "course": "BSc",
        "graduationPercentage": "59%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 4.04,
        "cgpa2": 5.74
    },
    {
        "id": 4,
        "rollNo": "2500460140004",
        "name": "Akash Katiyar",
        "gender": "Male",
        "phone": "8840758150",
        "tenthPercentage": "75.6%",
        "tenthBoard": "UP Board",
        "interPercentage": "67.8%",
        "interBoard": "UP",
        "course": "BSc",
        "graduationPercentage": "54.8%",
        "university": "CSJMU",
        "medium": "ENGLISH",
        "cgpa1": 6.96,
        "cgpa2": 7.65, "dob":"17-09-2001"
    },
    {
        "id": 5,
        "rollNo": "2500460140005",
        "name": "Akash Yadav",
        "gender": "Male",
        "phone": "9555229056",
        "tenthPercentage": "86.7%",
        "tenthBoard": "UP board",
        "interPercentage": "71%",
        "interBoard": "UP",
        "course": "BSc",
        "graduationPercentage": "69%",
        "university": "CSJMU",
        "medium": "Hindi",
        "cgpa1": 4.99,
        "cgpa2": 6.65
    },
    {
        "id": 6,
        "rollNo": "2500460140006",
        "name": "Aman Kumar",
        "gender": "Male",
        "phone": "9328663081",
        "tenthPercentage": "68%",
        "tenthBoard": "UP Board ",
        "interPercentage": "72%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "66.67%",
        "university": "CSJMU",
        "medium": "REGULAR/English ",
        "cgpa1": 6.96,
        "cgpa2": 7.74
    },
    {
        "id": 7,
        "rollNo": "2500460140007",
        "name": "Anshika Gautam",
        "gender": "Female",
        "phone": "8176090075",
        "tenthPercentage": "75%",
        "tenthBoard": "CBSE Board ",
        "interPercentage": "70%",
        "interBoard": "CBSC",
        "course": "B.Sc",
        "graduationPercentage": "80.2%",
        "university": "CSJMU",
        "medium": "English ",
        "cgpa1": 7.39,
        "cgpa2": 8.26
    },
    {
        "id": 8,
        "rollNo": "2500460140008",
        "name": "Anshu Pal",
        "gender": "Male",
        "phone": "9336312046",
        "tenthPercentage": "75.16%",
        "tenthBoard": "UP Board ",
        "interPercentage": "70%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "69.56%",
        "university": "csjmu",
        "medium": "Regular English ",
        "cgpa1": 6.67,
        "cgpa2": 8.26, "dob":"01-01-2006"
    },
    {
        "id": 9,
        "rollNo": "2500460140009",
        "name": "Anubhav Dixit",
        "gender": "Male",
        "phone": "9120914140",
        "tenthPercentage": "72.5%",
        "tenthBoard": "UP board",
        "interPercentage": "59.4%",
        "interBoard": "UP",
        "course": "BSc",
        "graduationPercentage": "74%",
        "university": "Lucknow university",
        "medium": "English",
        "cgpa1": 5.09,
        "cgpa2": 6.13
    },
    {
        "id": 10,
        "rollNo": "2500460140010",
        "name": "Anurag Pal",
        "gender": "Male",
        "phone": "9389390379",
        "tenthPercentage": "64%",
        "tenthBoard": "CBSE",
        "interPercentage": "79%",
        "interBoard": "CBSE",
        "course": "BSc",
        "graduationPercentage": "61%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 5.43,
        "cgpa2": 5.48
    },
    {
        "id": 11,
        "rollNo": "2500460140011",
        "name": "Aryan Rajput",
        "gender": "Male",
        "phone": "9506520139",
        "tenthPercentage": "75.16%",
        "tenthBoard": "UP Board",
        "interPercentage": "56.2%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "69.22%",
        "university": "Asian International University",
        "medium": "Regular/English ",
        "cgpa1": 7.3,
        "cgpa2": 7.83, "dob":"10-07-2005"
    },
    {
        "id": 12,
        "rollNo": "2500460140012",
        "name": "Avnish Yadav",
        "gender": "Male",
        "phone": "7757825633",
        "tenthPercentage": "88.2%",
        "tenthBoard": "CBSE",
        "interPercentage": "93.2%",
        "interBoard": "CBSE",
        "course": "BCA",
        "graduationPercentage": "78.8%",
        "university": "Symbiosis International University",
        "medium": "regular/english ",
        "cgpa1": 8,
        "cgpa2": 7.78, "dob":"28-12-2003"
    },
    {
        "id": 13,
        "rollNo": "2500460140013",
        "name": "Daksh Singh",
        "gender": "Male",
        "phone": "6386115458",
        "tenthPercentage": "79.5%",
        "tenthBoard": "UP Board ",
        "interPercentage": "68.8%",
        "interBoard": "UP",
        "course": "BSC",
        "graduationPercentage": "70%",
        "university": "CSJMU",
        "medium": "Regular /Hindi ",
        "cgpa1": 7.83,
        "cgpa2": 8.04
    },
    {
        "id": 14,
        "rollNo": "2500460140014",
        "name": "Deepak Katiyar",
        "gender": "Male",
        "phone": "8174826500",
        "tenthPercentage": "74.8%",
        "tenthBoard": "CBSE",
        "interPercentage": "70.4%",
        "interBoard": "CBSE",
        "course": "Computer Application",
        "graduationPercentage": "77.14%",
        "university": "CSJMU",
        "medium": "Regular/English",
        "cgpa1": 8.52,
        "cgpa2": 9, "dob":"24-04-2005"
    },
    {
        "id": 15,
        "rollNo": "2500460140015",
        "name": "Geetanjali",
        "gender": "Female",
        "phone": "6391772126",
        "tenthPercentage": "82%",
        "tenthBoard": "UP Board",
        "interPercentage": "70.4%",
        "interBoard": "UP Board",
        "course": "BSC",
        "graduationPercentage": "62.7%",
        "university": "BU jhanshi",
        "medium": "English",
        "cgpa1": 6.74,
        "cgpa2": 8.57, "dob":"14-11-2003"
    },
    {
        "id": 16,
        "rollNo": "2500460140016",
        "name": "Harsh Sahu",
        "gender": "Male",
        "phone": "6386677040",
        "tenthPercentage": "76%",
        "tenthBoard": "Up board",
        "interPercentage": "64%",
        "interBoard": "UP",
        "course": "BSC",
        "graduationPercentage": "58%",
        "university": "CSJMU",
        "medium": "Regular /English ",
        "cgpa1": 7.48,
        "cgpa2": 7.76
    },
    {
        "id": 17,
        "rollNo": "2500460140017",
        "name": "Hemant Kushwaha",
        "gender": "Male",
        "phone": "9793979479",
        "tenthPercentage": "64.83%",
        "tenthBoard": "UP Board ",
        "interPercentage": "65.6%",
        "interBoard": "UP",
        "course": "BSc",
        "graduationPercentage": "68.15%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 7.04,
        "cgpa2": 8.09, "dob":"30-11-2003"
    },
    {
        "id": 18,
        "rollNo": "2500460140018",
        "name": "Himanshu Pal",
        "gender": "Male",
        "phone": "8423794505",
        "tenthPercentage": "80%",
        "tenthBoard": "CBSE",
        "interPercentage": "80%",
        "interBoard": "CBSE",
        "course": "B.Sc",
        "graduationPercentage": "80%",
        "university": "CSJMU",
        "medium": "Hindi",
        "cgpa1": 6.48,
        "cgpa2": 7.13
    },
    {
        "id": 19,
        "rollNo": "2500460140019",
        "name": "Kavya Shukla",
        "gender": "Female",
        "phone": "9696116708",
        "tenthPercentage": "85.6%",
        "tenthBoard": "UP board ",
        "interPercentage": "73.2%",
        "interBoard": "UP",
        "course": "BSC ",
        "graduationPercentage": "87.7%",
        "university": "CSJMU ",
        "medium": "English ",
        "cgpa1": 7,
        "cgpa2": 8.43, "dob":"27-12-2006"
    },
    {
        "id": 20,
        "rollNo": "2500460140020",
        "name": "Khushi Sahu",
        "gender": "Female",
        "phone": "7307502454",
        "tenthPercentage": "85%",
        "tenthBoard": "UP board",
        "interPercentage": "71%",
        "interBoard": "UP",
        "course": "Bsc",
        "graduationPercentage": "77.6%",
        "university": "CSJMU ",
        "medium": "English",
        "cgpa1": 7.7,
        "cgpa2": 9, "dob":"03-07-2005"
    },
    {
        "id": 21,
        "rollNo": "2500460140021",
        "name": "Manas Bhandari",
        "gender": "Male",
        "phone": "9555802675",
        "tenthPercentage": "69%",
        "tenthBoard": "  UP",
        "interPercentage": "69%",
        "interBoard": "UP",
        "course": "Computer Application",
        "graduationPercentage": "68.17%",
        "university": "CSJMU",
        "medium": "ENGLISH",
        "cgpa1": 7.43,
        "cgpa2": 7.84, "dob":"19-11-2003"
    },
    {
        "id": 22,
        "rollNo": "2500460140022",
        "name": "Manshvi Gupta",
        "gender": "Female",
        "phone": "9528605531",
        "tenthPercentage": "91%",
        "tenthBoard": "CBSE ",
        "interPercentage": "82%",
        "interBoard": "CBSE",
        "course": "B.Sc",
        "graduationPercentage": "79.8%",
        "university": "DBRAU",
        "medium": "Regular/English ",
        "cgpa1": 8.43,
        "cgpa2": 9.04
    },
    {
        "id": 23,
        "rollNo": "2500460140023",
        "name": "Mayank Kushwaha",
        "gender": "Male",
        "phone": "8382906412",
        "tenthPercentage": "63.5%",
        "tenthBoard": "UP",
        "interPercentage": "66.2%",
        "interBoard": "UP",
        "course": "Computer Application ",
        "graduationPercentage": "68.69%",
        "university": "CSJMU",
        "medium": "ENGLISH ",
        "cgpa1": 7.26,
        "cgpa2": 8.43
    },
    {
        "id": 24,
        "rollNo": "2500460140024",
        "name": "Naman Trivedi",
        "gender": "Male",
        "phone": "6306787424",
        "tenthPercentage": "80%",
        "tenthBoard": "UP board",
        "interPercentage": "76.6%",
        "interBoard": "UP",
        "course": "B.Sc",
        "graduationPercentage": "75.5%",
        "university": "CSJMU",
        "medium": "ENGLISH",
        "cgpa1": 7.52,
        "cgpa2": 7.83
    },
    {
        "id": 25,
        "rollNo": "2500460140025",
        "name": "Nikhil Rajput",
        "gender": "Male",
        "phone": "7355391947",
        "tenthPercentage": "58%",
        "tenthBoard": "CBSE ",
        "interPercentage": "60%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "62.4%",
        "university": "CSJMU",
        "medium": "English ",
        "cgpa1": 6.26,
        "cgpa2": 7.09
    },
    {
        "id": 26,
        "rollNo": "2500460140026",
        "name": "Nikhil Tiwari",
        "gender": "Male",
        "phone": "8960415723",
        "tenthPercentage": "74%",
        "tenthBoard": "UP  Board",
        "interPercentage": "81%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "72%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 7.39,
        "cgpa2": 7.48
    },
    {
        "id": 27,
        "rollNo": "2500460140027",
        "name": "Nitish Soni",
        "gender": "Male",
        "phone": "7651997630",
        "tenthPercentage": "73%",
        "tenthBoard": "UP",
        "interPercentage": "65%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "62%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 7.09,
        "cgpa2": 7.65
    },
    {
        "id": 28,
        "rollNo": "2500460140028",
        "name": "Ojas Mishra",
        "gender": "Male",
        "phone": "8787078734",
        "tenthPercentage": "65%",
        "tenthBoard": "UP",
        "interPercentage": "60%",
        "interBoard": "UP",
        "course": "BSC ",
        "graduationPercentage": "75%",
        "university": "CSJMU",
        "medium": "English ",
        "cgpa1": 5.8,
        "cgpa2": 7.6
    },
    {
        "id": 29,
        "rollNo": "2500460140029",
        "name": "Parthiv Singh Patel",
        "gender": "Male",
        "phone": "8318168481",
        "tenthPercentage": "81%",
        "tenthBoard": "UP",
        "interPercentage": "73%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "76.8%",
        "university": "CSJMU",
        "medium": "English / Regular ",
        "cgpa1": 8.43,
        "cgpa2": 8.48
    },
    {
        "id": 30,
        "rollNo": "2500460140030",
        "name": "Payal Yadav",
        "gender": "Female",
        "phone": "8924815077",
        "tenthPercentage": "77.3%",
        "tenthBoard": "UP",
        "interPercentage": "73.8%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "70.47%",
        "university": "MCU",
        "medium": "English/Regular",
        "cgpa1": 5.48,
        "cgpa2": 7.4
    },
    {
        "id": 31,
        "rollNo": "2500460140032",
        "name": "Prateek Mishra",
        "gender": "Male",
        "phone": "8467047865",
        "tenthPercentage": "81%",
        "tenthBoard": "UP BOARD ",
        "interPercentage": "69%",
        "interBoard": "CBSE",
        "course": "B.Sc",
        "graduationPercentage": "70.85%",
        "university": "CSJMU",
        "medium": "English/Regular",
        "cgpa1": 6.61,
        "cgpa2": 6.74
    },
    {
        "id": 32,
        "rollNo": "2500460140033",
        "name": "Prateek Shukla",
        "gender": "Male",
        "phone": "8604682749",
        "tenthPercentage": "83%",
        "tenthBoard": "UP Board",
        "interPercentage": "83%",
        "interBoard": "UP Board",
        "course": 83,
        "graduationPercentage": "8.2.4",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 5.87,
        "cgpa2": 8.48
    },
    {
        "id": 33,
        "rollNo": "2500460140034",
        "name": "Prem Kumar Gond",
        "gender": "Male",
        "phone": "7275556145",
        "tenthPercentage": "76%",
        "tenthBoard": "UP Board ",
        "interPercentage": "50.4%",
        "interBoard": "UP",
        "course": "B.Com",
        "graduationPercentage": "58.75%",
        "university": "CSJMU",
        "medium": "Hindi / Regular ",
        "cgpa1": 7.13,
        "cgpa2": 8.35
    },
    {
        "id": 34,
        "rollNo": "2500460140035",
        "name": "Raghvendra Singh",
        "gender": "Male",
        "phone": "9580145529",
        "tenthPercentage": "68%",
        "tenthBoard": "UP Board",
        "interPercentage": "63%",
        "interBoard": "UP",
        "course": "Bsc",
        "graduationPercentage": "68%",
        "university": "CSJMU",
        "medium": "Hindi/ Regular",
        "cgpa1": 6.57,
        "cgpa2": 6.35, "dob":"15-12-2000"
    },
    {
        "id": 35,
        "rollNo": "2500460140036",
        "name": "Rahul",
        "gender": "Male",
        "phone": "6393759924",
        "tenthPercentage": "74.66%",
        "tenthBoard": "UP Board",
        "interPercentage": "78%",
        "interBoard": "up board",
        "course": "b.sc",
        "graduationPercentage": "55.67%",
        "university": "csjmu",
        "medium": "Hindi/ Regular",
        "cgpa1": 4.78,
        "cgpa2": 6.87
    },
    {
        "id": 36,
        "rollNo": "2500460140037",
        "name": "Rajeshwar Khatri",
        "gender": "Male",
        "phone": "9696405484",
        "tenthPercentage": "79.5%",
        "tenthBoard": "UP Board",
        "interPercentage": "73.8%",
        "interBoard": "UP",
        "course": "B.Sc",
        "graduationPercentage": "70.5%",
        "university": "CSJMU",
        "medium": "Hindi/ Regular",
        "cgpa1": 5.43,
        "cgpa2": 6.65
    },
    {
        "id": 37,
        "rollNo": "2500460140038",
        "name": "Ram Ji Katiyar",
        "gender": "Male",
        "phone": "9140706435",
        "tenthPercentage": "81%",
        "tenthBoard": "UP Board ",
        "interPercentage": "79%",
        "interBoard": "UP",
        "course": "Bsc ",
        "graduationPercentage": "74%",
        "university": "CSJMU",
        "medium": "English Regular ",
        "cgpa1": 4.35,
        "cgpa2": 7.61
    },
    {
        "id": 38,
        "rollNo": "2500460140039",
        "name": "Rishika Srivastava",
        "gender": "Female",
        "phone": "9305630784",
        "tenthPercentage": "86.8%",
        "tenthBoard": "UP board ",
        "interPercentage": "81%",
        "interBoard": "UP",
        "course": "Bachelor of Science ",
        "graduationPercentage": "67.5%",
        "university": "CSJMU",
        "medium": "English ",
        "cgpa1": 6.13,
        "cgpa2": 7.17
    },
    {
        "id": 39,
        "rollNo": "2500460140040",
        "name": "Sachin Kumar Upadhyay",
        "gender": "Male",
        "phone": "7007295396",
        "tenthPercentage": "62%",
        "tenthBoard": "CBSE",
        "interPercentage": "60%",
        "interBoard": "CBSE",
        "course": "BCA",
        "graduationPercentage": "70%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 7.09,
        "cgpa2": 7
    },
    {
        "id": 40,
        "rollNo": "2500460140041",
        "name": "Sakshi Yadav",
        "gender": "Female ",
        "phone": "7233025109",
        "tenthPercentage": "60%",
        "tenthBoard": "CBSE",
        "interPercentage": "64%",
        "interBoard": "CBSE ",
        "course": "BCA",
        "graduationPercentage": "68%",
        "university": "CSJMU ",
        "medium": "English ",
        "cgpa1": 6.26,
        "cgpa2": 6.87, "dob":"15-05-2004"
    },
    {
        "id": 41,
        "rollNo": "2500460140042",
        "name": "Shivam Rajput",
        "gender": "Male",
        "phone": "8299735328",
        "tenthPercentage": "61.3%",
        "tenthBoard": "UP Board ",
        "interPercentage": "67.6%",
        "interBoard": "UP",
        "course": "B.Sc",
        "graduationPercentage": "85%",
        "university": "CSJMU ",
        "medium": "Hindi/Regular ",
        "cgpa1": 5.83,
        "cgpa2": 5.35, "dob":"05-05-2003"
    },
    {
        "id": 42,
        "rollNo": "2500460140043",
        "name": "Shivam Yadav",
        "gender": "Male",
        "phone": "8303715984",
        "tenthPercentage": "72.4%",
        "tenthBoard": "UP Board ",
        "interPercentage": "73.6%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "69.9%",
        "university": "MCU",
        "medium": "English ",
        "cgpa1": 7.17,
        "cgpa2": 7.91, "dob":"20-07-2004"
    },
    {
        "id": 43,
        "rollNo": "2500460140044",
        "name": "Shomil Katiyar",
        "gender": "Male",
        "phone": "9696947551",
        "tenthPercentage": "76.8%",
        "tenthBoard": "UP Board ",
        "interPercentage": "76.8%",
        "interBoard": "UP",
        "course": "BCA ",
        "graduationPercentage": "75.2%",
        "university": "MCU ",
        "medium": "English ",
        "cgpa1": 7.83,
        "cgpa2": 8.09, "dob":"25-09-2006"
    },
    {
        "id": 44,
        "rollNo": "2500460140045",
        "name": "Shreshtha Rathore",
        "gender": "Male",
        "phone": "8887603403",
        "tenthPercentage": "84%",
        "tenthBoard": "CISCE",
        "interPercentage": "67%",
        "interBoard": "ISC",
        "course": "B.C.A.",
        "graduationPercentage": "72%",
        "university": "C.S.J.M.U.",
        "medium": "English",
        "cgpa1": 6.22,
        "cgpa2": 7.4
    },
    {
        "id": 45,
        "rollNo": "2500460140046",
        "name": "Sonakshi Porwal",
        "gender": "Female",
        "phone": "8115594996",
        "tenthPercentage": "82%",
        "tenthBoard": "up board ",
        "interPercentage": "73%",
        "interBoard": "UP board ",
        "course": "BSC",
        "graduationPercentage": "79%",
        "university": "CSJMU",
        "medium": "Hindi/ Regular",
        "cgpa1": 4.87,
        "cgpa2": 6.43
    },
    {
        "id": 46,
        "rollNo": "2500460140047",
        "name": "Subhant Mishra",
        "gender": "Male",
        "phone": "8126958318",
        "tenthPercentage": "80%",
        "tenthBoard": "UP Board ",
        "interPercentage": "74%",
        "interBoard": "UP Board ",
        "course": "BCA",
        "graduationPercentage": "74%",
        "university": "CSMU",
        "medium": "English ",
        "cgpa1": 5.61,
        "cgpa2": 7.04
    },
    {
        "id": 47,
        "rollNo": "2500460140048",
        "name": "Sumit Savita",
        "gender": "Male",
        "phone": "8318423348",
        "tenthPercentage": "84.16%",
        "tenthBoard": "UP",
        "interPercentage": "66%",
        "interBoard": "UP",
        "course": "BSC ",
        "graduationPercentage": "69%",
        "university": "CSJMU ",
        "medium": "english ",
        "cgpa1": 7.3,
        "cgpa2": 7.6
    },
    {
        "id": 48,
        "rollNo": "2500460140049",
        "name": "Tanish Sachan",
        "gender": "Female",
        "phone": "9219917522",
        "tenthPercentage": "73%",
        "tenthBoard": "UP",
        "interPercentage": "68.4%",
        "interBoard": "UP",
        "course": "BSC",
        "graduationPercentage": "52.11%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 7.9,
        "cgpa2": 8.3
    },
    {
        "id": 49,
        "rollNo": "2500460140050",
        "name": "Tanishka Gautam",
        "gender": "Female",
        "phone": "7307766388",
        "tenthPercentage": "74%",
        "tenthBoard": "UP board",
        "interPercentage": "64%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "72%",
        "university": "CSJMU",
        "medium": "English",
        "cgpa1": 8.1,
        "cgpa2": 8.7
    },
    {
        "id": 50,
        "rollNo": "2500460140051",
        "name": "Tejaswani Sharma",
        "gender": "Female",
        "phone": "9219424282",
        "tenthPercentage": "75%",
        "tenthBoard": "up board",
        "interPercentage": "60%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "60%",
        "university": "csjmu",
        "medium": "English ",
        "cgpa1": 5.51,
        "cgpa2": 5.3, "dob":"11-12-2004"
    },
    {
        "id": 51,
        "rollNo": "2500460140052",
        "name": "Utkrisht Dubey",
        "gender": "Male",
        "phone": "7392894227",
        "tenthPercentage": "64.83%",
        "tenthBoard": "UP Board ",
        "interPercentage": "55%",
        "interBoard": "UP",
        "course": "BCA",
        "graduationPercentage": "65%",
        "university": "CSJMU ",
        "medium": "English ",
        "cgpa1": 7.26,
        "cgpa2": 7.91
    }
];